// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	capabilities "github.com/alanshaw/libracha/capabilities"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *LocationArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Content (multihash.Multihash) (slice)
	if len("Content") > 8192 {
		return fmt.Errorf("String in field \"Content\" was too long")
	}
	if err := jw.WriteString(string("Content")); err != nil {
		return fmt.Errorf("\"Content\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Content) > 2097152 {
		return fmt.Errorf("Byte array in field t.Content was too long")
	}

	if err := jw.WriteBytes(t.Content); err != nil {
		return fmt.Errorf("t.Content: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Location ([]capabilities.CborURL) (slice)
	if len("Location") > 8192 {
		return fmt.Errorf("String in field \"Location\" was too long")
	}
	if err := jw.WriteString(string("Location")); err != nil {
		return fmt.Errorf("\"Location\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Location) > 8192 {
		return fmt.Errorf("Slice value in field t.Location was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Location: %w", err)
	}
	for i, v := range t.Location {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Location: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Location: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Range (datamodel.RangeModel) (struct)
	if len("Range") > 8192 {
		return fmt.Errorf("String in field \"Range\" was too long")
	}
	if err := jw.WriteString(string("Range")); err != nil {
		return fmt.Errorf("\"Range\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Range.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Range: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Space (did.DID) (struct)
	if len("Space") > 8192 {
		return fmt.Errorf("String in field \"Space\" was too long")
	}
	if err := jw.WriteString(string("Space")); err != nil {
		return fmt.Errorf("\"Space\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Space.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Space: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *LocationArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = LocationArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("LocationArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("LocationArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("LocationArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("LocationArgumentsModel: string too large")
				}
				return fmt.Errorf("LocationArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("LocationArgumentsModel: %w", err)
			}
			switch name {

			// t.Content (multihash.Multihash) (slice)
			case "Content":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Content: byte array too large")
						}
						return fmt.Errorf("t.Content: %w", err)
					}
					if len(bval) > 0 {
						t.Content = []uint8(bval)
					}
				}

				// t.Location ([]capabilities.CborURL) (slice)
			case "Location":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Location: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Location: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Location: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]capabilities.CborURL, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Location = append(t.Location, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Location: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Location: slice too large")
							}
						}
					}

				}

				// t.Range (datamodel.RangeModel) (struct)
			case "Range":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.Range: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.Range: %w", err)
						}
					} else {
						t.Range = new(RangeModel)
						if err := t.Range.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Range pointer: %w", err)
						}
					}
				}

				// t.Space (did.DID) (struct)
			case "Space":

				if err := t.Space.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Space: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("LocationArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("LocationArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("LocationArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *RangeModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Length (uint64) (uint64)
	if len("Length") > 8192 {
		return fmt.Errorf("String in field \"Length\" was too long")
	}
	if err := jw.WriteString(string("Length")); err != nil {
		return fmt.Errorf("\"Length\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.Length == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("t.Length: %w", err)
		}
	} else {
		if err := jw.WriteUint64(uint64(*t.Length)); err != nil {
			return fmt.Errorf("t.Length: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Offset (uint64) (uint64)
	if len("Offset") > 8192 {
		return fmt.Errorf("String in field \"Offset\" was too long")
	}
	if err := jw.WriteString(string("Offset")); err != nil {
		return fmt.Errorf("\"Offset\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Offset)); err != nil {
		return fmt.Errorf("t.Offset: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RangeModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RangeModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("RangeModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("RangeModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("RangeModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("RangeModel: string too large")
				}
				return fmt.Errorf("RangeModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("RangeModel: %w", err)
			}
			switch name {

			// t.Length (uint64) (uint64)
			case "Length":
				{

					nval, err := jr.ReadNumberAsUint64OrNull()
					if err != nil {
						return fmt.Errorf("t.Length: %w", err)
					}
					if nval != nil {
						typed := uint64(*nval)
						t.Length = &typed
					}

				}

				// t.Offset (uint64) (uint64)
			case "Offset":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("t.Offset: %w", err)
					}
					t.Offset = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("RangeModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("RangeModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("RangeModel: map too large")
			}
		}
	}

	return nil
}
