// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	promise "github.com/alanshaw/ucantone/ucan/promise"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AllocateArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("String in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("\"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cause (cid.Cid) (struct)
	if len("cause") > 8192 {
		return fmt.Errorf("String in field \"cause\" was too long")
	}
	if err := jw.WriteString(string("cause")); err != nil {
		return fmt.Errorf("\"cause\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Cause); err != nil {
		return fmt.Errorf("t.Cause: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AllocateArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AllocateArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AllocateArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AllocateArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AllocateArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AllocateArgumentsModel: string too large")
				}
				return fmt.Errorf("AllocateArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AllocateArgumentsModel: %w", err)
			}
			switch name {

			// t.Blob (datamodel.BlobModel) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Cause (cid.Cid) (struct)
			case "cause":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.Cause: %w", err)
					}
					t.Cause = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AllocateArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AllocateArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AllocateArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *BlobModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("String in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("\"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("Byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("t.Digest: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return fmt.Errorf("String in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("\"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Size)); err != nil {
		return fmt.Errorf("t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *BlobModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("BlobModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("BlobModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("BlobModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("BlobModel: string too large")
				}
				return fmt.Errorf("BlobModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("BlobModel: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Digest: byte array too large")
						}
						return fmt.Errorf("t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("t.Size: %w", err)
					}
					t.Size = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("BlobModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("BlobModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("BlobModel: map too large")
			}
		}
	}

	return nil
}
func (t *AllocateOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Address (datamodel.BlobAddressModel) (struct)
	if t.Address != nil {
		if len("address") > 8192 {
			return fmt.Errorf("String in field \"address\" was too long")
		}
		if err := jw.WriteString(string("address")); err != nil {
			return fmt.Errorf("\"address\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Address.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.Address: %w", err)
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return fmt.Errorf("String in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("\"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Size)); err != nil {
		return fmt.Errorf("t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AllocateOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AllocateOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AllocateOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AllocateOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AllocateOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AllocateOKModel: string too large")
				}
				return fmt.Errorf("AllocateOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AllocateOKModel: %w", err)
			}
			switch name {

			// t.Address (datamodel.BlobAddressModel) (struct)
			case "address":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.Address: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.Address: %w", err)
						}
					} else {
						t.Address = new(BlobAddressModel)
						if err := t.Address.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Address pointer: %w", err)
						}
					}
				}

				// t.Size (uint64) (uint64)
			case "size":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("t.Size: %w", err)
					}
					t.Size = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AllocateOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AllocateOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AllocateOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *BlobAddressModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Expires (capabilities.CborTime) (struct)
	if len("expires") > 8192 {
		return fmt.Errorf("String in field \"expires\" was too long")
	}
	if err := jw.WriteString(string("expires")); err != nil {
		return fmt.Errorf("\"expires\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Expires.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Expires: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Headers (map[string]string) (map)
	if len("headers") > 8192 {
		return fmt.Errorf("String in field \"headers\" was too long")
	}
	if err := jw.WriteString(string("headers")); err != nil {
		return fmt.Errorf("\"headers\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Headers) > 4096 {
			return fmt.Errorf("cannot marshal t.Headers map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("t.Headers: %w", err)
		}

		keys := make([]string, 0, len(t.Headers))
		for k := range t.Headers {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("t.Headers: %w", err)
				}
			}
			v := t.Headers[k]
			if len(k) > 8192 {
				return fmt.Errorf("String in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("t.Headers: %w", err)
			}

			if len(v) > 8192 {
				return fmt.Errorf("String in field v was too long")
			}
			if err := jw.WriteString(string(v)); err != nil {
				return fmt.Errorf("v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("t.Headers: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.URL (capabilities.CborURL) (struct)
	if len("url") > 8192 {
		return fmt.Errorf("String in field \"url\" was too long")
	}
	if err := jw.WriteString(string("url")); err != nil {
		return fmt.Errorf("\"url\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.URL.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.URL: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *BlobAddressModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BlobAddressModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("BlobAddressModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("BlobAddressModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("BlobAddressModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("BlobAddressModel: string too large")
				}
				return fmt.Errorf("BlobAddressModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("BlobAddressModel: %w", err)
			}
			switch name {

			// t.Expires (capabilities.CborTime) (struct)
			case "expires":

				if err := t.Expires.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Expires: %w", err)
				}

				// t.Headers (map[string]string) (map)
			case "headers":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("t.Headers: %w", err)
				}

				t.Headers = map[string]string{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("t.Headers: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("t.Headers: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("k: string too long")
								}
								return fmt.Errorf("k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("t.Headers: %w", err)
						}
						var v string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("v: string too long")
								}
								return fmt.Errorf("v: %w", err)
							}
							v = string(sval)
						}
						t.Headers[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("t.Headers: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.URL (capabilities.CborURL) (struct)
			case "url":

				if err := t.URL.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.URL: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("BlobAddressModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("BlobAddressModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("BlobAddressModel: map too large")
			}
		}
	}

	return nil
}
func (t *AcceptArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Put (promise.AwaitOK) (struct)
	if len("_put") > 8192 {
		return fmt.Errorf("String in field \"_put\" was too long")
	}
	if err := jw.WriteString(string("_put")); err != nil {
		return fmt.Errorf("\"_put\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Put.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Put: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("String in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("\"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Blob: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AcceptArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AcceptArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AcceptArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AcceptArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AcceptArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AcceptArgumentsModel: string too large")
				}
				return fmt.Errorf("AcceptArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AcceptArgumentsModel: %w", err)
			}
			switch name {

			// t.Put (promise.AwaitOK) (struct)
			case "_put":

				if err := t.Put.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Put: %w", err)
				}

				// t.Blob (datamodel.BlobModel) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AcceptArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AcceptArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AcceptArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *AcceptOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Site (cid.Cid) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("String in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("\"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Site); err != nil {
		return fmt.Errorf("t.Site: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AcceptOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AcceptOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AcceptOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AcceptOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AcceptOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AcceptOKModel: string too large")
				}
				return fmt.Errorf("AcceptOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AcceptOKModel: %w", err)
			}
			switch name {

			// t.Site (cid.Cid) (struct)
			case "site":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.Site: %w", err)
					}
					t.Site = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AcceptOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AcceptOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AcceptOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *AddArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("String in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("\"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Blob: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AddArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AddArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AddArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AddArgumentsModel: string too large")
				}
				return fmt.Errorf("AddArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AddArgumentsModel: %w", err)
			}
			switch name {

			// t.Blob (datamodel.BlobModel) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AddArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AddArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AddArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *AddOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Site (promise.AwaitOK) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("String in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("\"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Site.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Site: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AddOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AddOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AddOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AddOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AddOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AddOKModel: string too large")
				}
				return fmt.Errorf("AddOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AddOKModel: %w", err)
			}
			switch name {

			// t.Site (promise.AwaitOK) (struct)
			case "site":

				if err := t.Site.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Site: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AddOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AddOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AddOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *RemoveArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("String in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("\"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("Byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("t.Digest: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RemoveArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RemoveArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("RemoveArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("RemoveArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("RemoveArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("RemoveArgumentsModel: string too large")
				}
				return fmt.Errorf("RemoveArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("RemoveArgumentsModel: %w", err)
			}
			switch name {

			// t.Digest (multihash.Multihash) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Digest: byte array too large")
						}
						return fmt.Errorf("t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("RemoveArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("RemoveArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("RemoveArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *RemoveOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RemoveOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RemoveOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("RemoveOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("RemoveOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("RemoveOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("RemoveOKModel: string too large")
				}
				return fmt.Errorf("RemoveOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("RemoveOKModel: %w", err)
			}
			switch name {
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("RemoveOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("RemoveOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("RemoveOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *ReplicateArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Blob (datamodel.BlobModel) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("String in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("\"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Blob: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Replicas (uint64) (uint64)
	if len("replicas") > 8192 {
		return fmt.Errorf("String in field \"replicas\" was too long")
	}
	if err := jw.WriteString(string("replicas")); err != nil {
		return fmt.Errorf("\"replicas\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Replicas)); err != nil {
		return fmt.Errorf("t.Replicas: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Site (cid.Cid) (struct)
	if len("site") > 8192 {
		return fmt.Errorf("String in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("\"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Site); err != nil {
		return fmt.Errorf("t.Site: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ReplicateArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ReplicateArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ReplicateArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ReplicateArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ReplicateArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ReplicateArgumentsModel: string too large")
				}
				return fmt.Errorf("ReplicateArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ReplicateArgumentsModel: %w", err)
			}
			switch name {

			// t.Blob (datamodel.BlobModel) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Replicas (uint64) (uint64)
			case "replicas":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("t.Replicas: %w", err)
					}
					t.Replicas = uint64(nval)

				}

				// t.Site (cid.Cid) (struct)
			case "site":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.Site: %w", err)
					}
					t.Site = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ReplicateArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ReplicateArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ReplicateArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *ReplicateOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Site ([]promise.AwaitOK) (slice)
	if len("site") > 8192 {
		return fmt.Errorf("String in field \"site\" was too long")
	}
	if err := jw.WriteString(string("site")); err != nil {
		return fmt.Errorf("\"site\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Site) > 8192 {
		return fmt.Errorf("Slice value in field t.Site was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Site: %w", err)
	}
	for i, v := range t.Site {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Site: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Site: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ReplicateOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ReplicateOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ReplicateOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ReplicateOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ReplicateOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ReplicateOKModel: string too large")
				}
				return fmt.Errorf("ReplicateOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ReplicateOKModel: %w", err)
			}
			switch name {

			// t.Site ([]promise.AwaitOK) (slice)
			case "site":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Site: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Site: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Site: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]promise.AwaitOK, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Site = append(t.Site, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Site: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Site: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ReplicateOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ReplicateOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ReplicateOKModel: map too large")
			}
		}
	}

	return nil
}
