// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *ListArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Cursor (string) (string)
	if t.Cursor != nil {
		if len("cursor") > 8192 {
			return fmt.Errorf("String in field \"cursor\" was too long")
		}
		if err := jw.WriteString(string("cursor")); err != nil {
			return fmt.Errorf("\"cursor\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if t.Cursor == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("t.Cursor: %w", err)
			}
		} else {
			if len(*t.Cursor) > 8192 {
				return fmt.Errorf("String in field t.Cursor was too long")
			}
			if err := jw.WriteString(string(*t.Cursor)); err != nil {
				return fmt.Errorf("t.Cursor: %w", err)
			}
		}
		written++
	}
	if t.Size != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Size (int64) (int64)
	if t.Size != nil {
		if len("size") > 8192 {
			return fmt.Errorf("String in field \"size\" was too long")
		}
		if err := jw.WriteString(string("size")); err != nil {
			return fmt.Errorf("\"size\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}

		if t.Size == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("t.Size: %w", err)
			}
		} else {
			if err := jw.WriteInt64(int64(*t.Size)); err != nil {
				return fmt.Errorf("t.Size: %w", err)
			}
		}

		written++
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ListArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ListArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ListArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ListArgumentsModel: string too large")
				}
				return fmt.Errorf("ListArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ListArgumentsModel: %w", err)
			}
			switch name {

			// t.Cursor (string) (string)
			case "cursor":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Cursor: string too long")
						}
						return fmt.Errorf("t.Cursor: %w", err)
					}
					if sval != nil {
						t.Cursor = (*string)(sval)
					}
				}

				// t.Size (int64) (int64)
			case "size":
				{

					nval, err := jr.ReadNumberAsInt64OrNull()
					if err != nil {
						return fmt.Errorf("t.Size: %w", err)
					}
					if nval != nil {
						typed := int64(*nval)
						t.Size = &typed
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ListArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ListArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ListArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *ListOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Cursor (string) (string)
	if t.Cursor != nil {
		if len("cursor") > 8192 {
			return fmt.Errorf("String in field \"cursor\" was too long")
		}
		if err := jw.WriteString(string("cursor")); err != nil {
			return fmt.Errorf("\"cursor\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if t.Cursor == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("t.Cursor: %w", err)
			}
		} else {
			if len(*t.Cursor) > 8192 {
				return fmt.Errorf("String in field t.Cursor was too long")
			}
			if err := jw.WriteString(string(*t.Cursor)); err != nil {
				return fmt.Errorf("t.Cursor: %w", err)
			}
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Results ([]cid.Cid) (slice)
	if len("results") > 8192 {
		return fmt.Errorf("String in field \"results\" was too long")
	}
	if err := jw.WriteString(string("results")); err != nil {
		return fmt.Errorf("\"results\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Results) > 8192 {
		return fmt.Errorf("Slice value in field t.Results was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Results: %w", err)
	}
	for i, v := range t.Results {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Results: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Results: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Size (int64) (int64)
	if len("size") > 8192 {
		return fmt.Errorf("String in field \"size\" was too long")
	}
	if err := jw.WriteString(string("size")); err != nil {
		return fmt.Errorf("\"size\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Size)); err != nil {
		return fmt.Errorf("t.Size: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ListOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ListOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ListOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ListOKModel: string too large")
				}
				return fmt.Errorf("ListOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ListOKModel: %w", err)
			}
			switch name {

			// t.Cursor (string) (string)
			case "cursor":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Cursor: string too long")
						}
						return fmt.Errorf("t.Cursor: %w", err)
					}
					if sval != nil {
						t.Cursor = (*string)(sval)
					}
				}

				// t.Results ([]cid.Cid) (slice)
			case "results":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Results: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Results: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Results: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("item[0]: %w", err)
								}
								item[0] = c

							}
							t.Results = append(t.Results, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Results: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Results: slice too large")
							}
						}
					}

				}

				// t.Size (int64) (int64)
			case "size":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("t.Size: %w", err)
					}
					t.Size = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ListOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ListOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ListOKModel: map too large")
			}
		}
	}

	return nil
}
