// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *CacheArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Claim (cid.Cid) (struct)
	if len("claim") > 8192 {
		return fmt.Errorf("String in field \"claim\" was too long")
	}
	if err := jw.WriteString(string("claim")); err != nil {
		return fmt.Errorf("\"claim\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Claim); err != nil {
		return fmt.Errorf("t.Claim: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Provider (datamodel.ProviderModel) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("String in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("\"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Provider: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *CacheArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = CacheArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("CacheArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("CacheArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("CacheArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("CacheArgumentsModel: string too large")
				}
				return fmt.Errorf("CacheArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("CacheArgumentsModel: %w", err)
			}
			switch name {

			// t.Claim (cid.Cid) (struct)
			case "claim":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.Claim: %w", err)
					}
					t.Claim = c

				}

				// t.Provider (datamodel.ProviderModel) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("CacheArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("CacheArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("CacheArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *CacheOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *CacheOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = CacheOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("CacheOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("CacheOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("CacheOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("CacheOKModel: string too large")
				}
				return fmt.Errorf("CacheOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("CacheOKModel: %w", err)
			}
			switch name {
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("CacheOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("CacheOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("CacheOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *ProviderModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Addresses ([][]uint8) (slice)
	if len("addresses") > 8192 {
		return fmt.Errorf("String in field \"addresses\" was too long")
	}
	if err := jw.WriteString(string("addresses")); err != nil {
		return fmt.Errorf("\"addresses\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Addresses) > 8192 {
		return fmt.Errorf("Slice value in field t.Addresses was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Addresses: %w", err)
	}
	for i, v := range t.Addresses {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Addresses: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("Byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Addresses: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ProviderModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ProviderModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ProviderModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ProviderModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ProviderModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ProviderModel: string too large")
				}
				return fmt.Errorf("ProviderModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ProviderModel: %w", err)
			}
			switch name {

			// t.Addresses ([][]uint8) (slice)
			case "addresses":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Addresses: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Addresses: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Addresses: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("item[0]: byte array too large")
									}
									return fmt.Errorf("item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Addresses = append(t.Addresses, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Addresses: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Addresses: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ProviderModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ProviderModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ProviderModel: map too large")
			}
		}
	}

	return nil
}
